from datetime import datetime

from app.database.database import get_connection


def generate_report(user_input: str) -> dict:
    """
    Generate and save a cybersecurity report.
    """

    report = {
        "title": f"CyberGuard Report - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "report_type": "Cybersecurity Incident",
        "content": f"""
CyberGuard AI Incident Report

Summary
-------
{user_input}

Assessment
----------
The provided information was analyzed by CyberGuard AI.

Recommendations
---------------
• Investigate the reported activity.
• Preserve any available evidence.
• Change affected passwords if credentials may have been exposed.
• Enable Multi-Factor Authentication.
• Monitor accounts for suspicious activity.

Generated by CyberGuard AI.
""".strip(),
    }

    connection = get_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            INSERT INTO reports(
                title,
                report_type,
                content
            )
            VALUES (?, ?, ?)
            """,
            (
                report["title"],
                report["report_type"],
                report["content"],
            ),
        )

        connection.commit()

        report["report_id"] = cursor.lastrowid

        return report

    finally:

        connection.close()


def get_reports() -> list[tuple]:
    """
    Return all saved reports.
    """

    connection = get_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT
                id,
                title,
                report_type,
                content,
                created_at
            FROM reports
            ORDER BY created_at DESC
            """
        )

        return cursor.fetchall()

    finally:

        connection.close()